//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CastleAdventureResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CastleAdventureResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Castle.CastleAdventureResources", typeof(CastleAdventureResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle Adventure.
        /// </summary>
        internal static string CastleAdventureTitle {
            get {
                return ResourceManager.GetString("CastleAdventureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have collected these Treasures....
        /// </summary>
        internal static string CollectedTreasures {
            get {
                return ResourceManager.GetString("CollectedTreasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT???.
        /// </summary>
        internal static string CommandError {
            get {
                return ResourceManager.GetString("CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string CommandPrompt {
            get {
                return ResourceManager.GetString("CommandPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string EmptySpace {
            get {
                return ResourceManager.GetString("EmptySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve Escaped the Castle!.
        /// </summary>
        internal static string EscapedCastle {
            get {
                return ResourceManager.GetString("EscapedCastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve have failed to Escape!.
        /// </summary>
        internal static string FailedGame {
            get {
                return ResourceManager.GetString("FailedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I - for instructions.
        /// </summary>
        internal static string IForInstructions {
            get {
                return ResourceManager.GetString("IForInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    You are trapped in a deserted Castle.
        /// </summary>
        internal static string Intro1 {
            get {
                return ResourceManager.GetString("Intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just  run  into  them,  but only if you.
        /// </summary>
        internal static string Intro10 {
            get {
                return ResourceManager.GetString("Intro10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to have a weapon.The computer accepts most.
        /// </summary>
        internal static string Intro11 {
            get {
                return ResourceManager.GetString("Intro11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two word commands. There are 83 rooms &amp;.
        /// </summary>
        internal static string Intro12 {
            get {
                return ResourceManager.GetString("Intro12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 treasures..
        /// </summary>
        internal static string Intro13 {
            get {
                return ResourceManager.GetString("Intro13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  one hint:Look at everything carefully!.
        /// </summary>
        internal static string Intro14 {
            get {
                return ResourceManager.GetString("Intro14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and you must escape. It is rumored that.
        /// </summary>
        internal static string Intro2 {
            get {
                return ResourceManager.GetString("Intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the castle is  full of treasures.  Can.
        /// </summary>
        internal static string Intro3 {
            get {
                return ResourceManager.GetString("Intro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you find them all?.
        /// </summary>
        internal static string Intro4 {
            get {
                return ResourceManager.GetString("Intro4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the cursor keypad to move your man.
        /// </summary>
        internal static string Intro5 {
            get {
                return ResourceManager.GetString("Intro5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to around the rooms.  To pick up a visible.
        /// </summary>
        internal static string Intro6 {
            get {
                return ResourceManager.GetString("Intro6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item,  just run into it.  To pick up an.
        /// </summary>
        internal static string Intro7 {
            get {
                return ResourceManager.GetString("Intro7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item not displayed  on  the screen, use.
        /// </summary>
        internal static string Intro8 {
            get {
                return ResourceManager.GetString("Intro8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the command  GET.  To  attack  monsters.
        /// </summary>
        internal static string Intro9 {
            get {
                return ResourceManager.GetString("Intro9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have killed these Monsters.......
        /// </summary>
        internal static string KilledMonsters {
            get {
                return ResourceManager.GetString("KilledMonsters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEAD {0}.
        /// </summary>
        internal static string MosterDead {
            get {
                return ResourceManager.GetString("MosterDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1550 is perfect).
        /// </summary>
        internal static string PerfectScore {
            get {
                return ResourceManager.GetString("PerfectScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY AGAIN (Y/N)?.
        /// </summary>
        internal static string PlayAgain {
            get {
                return ResourceManager.GetString("PlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue.
        /// </summary>
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Press any key -.
        /// </summary>
        internal static string PressAnyKey2 {
            get {
                return ResourceManager.GetString("PressAnyKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P - to play.
        /// </summary>
        internal static string PToPlay {
            get {
                return ResourceManager.GetString("PToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve ended the game!.
        /// </summary>
        internal static string QuitGame {
            get {
                return ResourceManager.GetString("QuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Score: {0}.
        /// </summary>
        internal static string YourScore {
            get {
                return ResourceManager.GetString("YourScore", resourceCulture);
            }
        }
    }
}
